version: "3.9"
services:
  # Sink stack
  sink:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    depends_on:
      - postgres
    volumes:
      # Mount a volume under the shared nginx dir to serve static files
      - ./static/:/usr/share/nginx/html/
    restart: unless-stopped
  sink-nginx:
    image: nginx:latest
    hostname: sink-nginx
    volumes:
      # Mount the same volume to serve static files
      - ./static/:/usr/share/nginx/html/:ro
    ports:
      - 80:80
    restart: unless-stopped
  postgres:
    image: postgres:latest
    hostname: postgres
    env_file: .env
    volumes:
      - postgres-sink-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432

volumes:
  postgres-sink-data:
    name: postgres-sink-data